name: Terraform Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Entorno a desplegar"
        required: true
        default: "dev"
        type: choice
        options: [dev, prod]
      auto_approve:
        description: "Aprobar automáticamente (solo para dev)"
        required: false
        default: false
        type: boolean

env:
  AWS_REGION: us-west-1
  TERRAFORM_PLAN_JSON_FILE: tfplan.json

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

jobs:
  terraform-validation:
    name: "Validate & Plan"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for Validation & Plan
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify environment directory
        run: |
          echo "Entorno seleccionado: ${{ github.event.inputs.environment }}"
          ls -la environments/${{ github.event.inputs.environment }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform init -input=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Initialize TFLint plugins
        run: tflint --init

      - name: Run TFLint
        run: tflint --config=${{ github.workspace }}/.tflint.hcl --recursive

      - name: Terraform Plan and Convert to JSON
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: |
          terraform plan \
            -input=false \
            -var-file=terraform.tfvars \
            -out=tfplan.binary 
          
          terraform show -json tfplan.binary > ${{ env.TERRAFORM_PLAN_JSON_FILE }}
          
          # Opcional: verificar que el archivo JSON se creó
          ls -l ${{ env.TERRAFORM_PLAN_JSON_FILE }}
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Upload Terraform Plan JSON
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-json-${{ github.event.inputs.environment }} # Nombre del artefacto actualizado
          path: ./environments/${{ github.event.inputs.environment }}/${{ env.TERRAFORM_PLAN_JSON_FILE }} # Ruta al archivo JSON

  security-scans:
    name: "Security Scans"
    needs: terraform-validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Terraform Plan JSON
        uses: actions/download-artifact@v4
        with:
          name: tfplan-json-${{ github.event.inputs.environment }}
          path: ./environments/${{ github.event.inputs.environment }}

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          working_directory : ./environments/${{ github.event.inputs.environment }}
          sarif_file: tfsec-results.sarif

      - name: Upload tfsec results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec-results.sarif

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12 
        with:
          file: ./environments/${{ github.event.inputs.environment }}/${{ env.TERRAFORM_PLAN_JSON_FILE }}
          framework: terraform_plan 
          output_format: sarif
          output_file_path: checkov.sarif 
          soft_fail: true 

      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif/results_sarif.sarif