name: Terraform Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno a desplegar'
        required: true
        default: 'dev'
        type: choice
        options: [dev, prod]
      auto_approve:
        description: 'Aprobar automáticamente?'
        required: false
        default: 'false'
        type: boolean

env:
  AWS_REGION: us-west-1

jobs:
  validate-and-plan:
    name: Validate, Lint & Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/${{ github.event.inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Environment Directory
        working-directory: ${{ github.workspace }}
        run: |
          echo "Verificando directorio: environments/${{ github.event.inputs.environment }}"
          if [ ! -d "environments/${{ github.event.inputs.environment }}" ]; then
            echo "::error::Directorio environments/${{ github.event.inputs.environment }} no encontrado"
            exit 1
          fi

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint
        working-directory: ${{ github.workspace }}
        run: tflint --config=.tflint.hcl --recursive ./environments/${{ github.event.inputs.environment }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.event.inputs.environment }}
          path: ./environments/${{ github.event.inputs.environment }}/tfplan

  security-scans:
    name: Security Scanning
    needs: validate-and-plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ github.event.inputs.environment }}
          path: ./environments/${{ github.event.inputs.environment }}

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.1.0
        with:
          plan_file: ./environments/${{ github.event.inputs.environment }}/tfplan
          format: table
          output: tfsec-results.txt

      - name: Upload tfsec Report
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-report-${{ github.event.inputs.environment }}
          path: tfsec-results.txt

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          file: ./environments/${{ github.event.inputs.environment }}/tfplan
          framework: terraform_plan
          output_format: sarif
          output_file_path: checkov.sarif

      - name: Upload Checkov Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report-${{ github.event.inputs.environment }}
          path: checkov.sarif

  terraform-apply:
    name: Terraform Apply
    if: ${{ github.event.inputs.auto_approve == 'true' && contains('dev prod', github.event.inputs.environment) }}
    needs: security-scans
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ./environments/${{ github.event.inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ github.event.inputs.environment }}
          path: ./environments/${{ github.event.inputs.environment }}

      - name: AWS OIDC Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan