name: Terraform Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Entorno a desplegar"
        required: true
        default: "dev"
        type: choice
        options: [dev, prod]
      auto_approve:
        description: "Aprobar automáticamente (solo para dev)"
        required: false
        default: false
        type: boolean

env:
  AWS_REGION: us-west-1

permissions:
  contents: read
  id-token: write

jobs:
  terraform-validation:
    name: "Validate & Plan"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Configure AWS Credentials for Validation & Plan
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify environment directory
        run: |
          echo "Entorno seleccionado: ${{ github.event.inputs.environment }}"
          ls -la environments/${{ github.event.inputs.environment }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform init -input=false

      - name: Terraform Format Check
        #working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Initialize TFLint plugins
        run: tflint --init

      - name: Run TFLint
        run: tflint --config=${{ github.workspace }}/.tflint.hcl --recursive

      - name: Terraform Plan
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: |
          terraform plan \
            -input=false \
            -var-file=terraform.tfvars \
            -out=tfplan
          echo "PLAN_FILE=tfplan" >> $GITHUB_ENV
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.event.inputs.environment }}
          path: ./environments/${{ github.event.inputs.environment }}/tfplan

  security-scans:
    name: "Security Scans"
    needs: terraform-validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ github.event.inputs.environment }}
          path: ./environments/${{ github.event.inputs.environment }}

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          working_directory : ./environments/${{ github.event.inputs.environment }}
          sarif_file: tfsec-results.sarif

      - name: Upload tfsec results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec-results.sarif

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          file: ./environments/${{ github.event.inputs.environment }}/tfplan
          framework: terraform_plan
          output_format: sarif
          output_file_path: checkov.sarif

      - name: Upload Checkov results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif

  terraform-apply:
    name: "Apply Changes"
    needs: [terraform-validation, security-scans]
    if: ${{ github.event.inputs.auto_approve == 'true' }}
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment }}
      url: https://github.com/JesquivelR/terraform-cicd/deployments
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ github.event.inputs.environment }}
          path: ./environments/${{ github.event.inputs.environment }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform

      - name: Terraform Apply
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform apply -input=false -auto-approve tfplan